# Generated by Django 6.0.6 on 2026-08-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên dịch vụ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Giá')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Thời lượng (phút)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ngắn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang phục vụ')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'db_table': 'poppy_offering',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên')),
                ('type_label', models.CharField(blank=True, max_length=60, verbose_name='Loại (thợ/bàn/bác sĩ...)')),
                ('specialty', models.CharField(blank=True, max_length=255, verbose_name='Chuyên môn')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Sức chứa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang nhận khách')),
            ],
            options={
                'verbose_name': 'Nguồn lực',
                'verbose_name_plural': 'Nguồn lực',
                'db_table': 'poppy_resource',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Tên khách')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Số điện thoại')),
                ('offering', models.CharField(blank=True, max_length=120, verbose_name='Dịch vụ')),
                ('resource', models.CharField(blank=True, max_length=120, verbose_name='Nguồn lực yêu cầu')),
                ('appointment_time_text', models.CharField(blank=True, max_length=120, verbose_name='Thời gian (khách nói)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hẹn')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('source', models.CharField(choices=[('chat', 'Chat'), ('voice', 'Gọi điện')], default='chat', max_length=10)),
                ('status', models.CharField(choices=[('new', 'Mới'), ('confirmed', 'Đã xác nhận'), ('done', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'db_table': 'poppy_booking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='poppy_booki_phone_ce4ead_idx'), models.Index(fields=['start_time'], name='poppy_booki_start_t_e63a3f_idx')],
            },
        ),
    ]
